# Manifiesto Kubernetes para el servicio de inventario
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
      - name: inventario
        image: toleraciafallas/inventario:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "database-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "inventario_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
---
apiVersion: v1
kind: Service
metadata:
  name: inventario-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: inventario